# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: "Tod Thomson's Blog"
description: "A blog about my development experiences in Microsoft's ecosystem"
tagline: 'The incoherent babbling of some random...'
url: http://todthomson.com
baseurl: /

# Feed
copyright: '2015-2016 Tod Thomson'
feed: feed.xml
avatar: public/images/avatar.png

# Author
author:
  name: 'Tod Thomson'
  url: https://twitter.com/todthomson
  email: tod@todthomson.com

# Pagination
paginate: 1

# Custom Variables
version: 0.0.2

github: https://github.com/todthomson
  repo:
