# Dependencies
markdown: kramdown # or redcarpet
highlighter: rouge # or pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
url: http://c0ntinuum.github.io
baseurl: /
paginate: 5
