# Dependencies
markdown: kramdown
highlighter: pygments # need to switch to rouge when github pages supports it

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title: "Tod Thomson's Blog"
tagline: 'TAGLINE'
description: 'DESCRIPTION'
url: http://blog.todthomson.com # http://todthomson.com or http://c0ntinuum.github.io
baseurl: /

author:
  name: 'Tod Thomson'
  url: https://twitter.com/todthomson

paginate: 5

# Custom vars
version: 0.0.1

github:
  repo: https://github.com/c0ntinuum
