# Dependencies
markdown: kramdown
highlighter: rouge

# Plugins
plugins: [jekyll-paginate]

# Permalinks
permalink: pretty

# Setup
title: "Tod Thomson's Blog"
description: "A blog about my development experiences in Microsoft's ecosystem"
tagline: 'The incoherent babbling of some random...'
url: http://todthomson.com
repository: "todthomson/todthomson.github.io"

# Feed
copyright: '2016 Tod Thomson'
feed: feed.xml
avatar: /public/images/avatar.jpg

# Author
author:
  name: 'Tod Thomson'
  url: https://twitter.com/todthomson
  email: tod@todthomson.com

# Pagination
paginate: 5
