# Site settings
title: Tod Thomson's Blog
email: todthomson@me.com
description: > # this means to ignore newlines until "baseurl:"
  Senior Developer @ Readify (http://readify.net) Pragmatic Programmer, Software Craftsman, Technologist, Magic Player...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://c0ntinuum.github.io" # the base hostname & protocol for your site
twitter_username: todthomson
github_username:  c0ntinuum

# Build settings
markdown: kramdown
highlighter: pygments
